### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/app-search-firestore-extension#1]
- [x] Add tests
- [x] Add linting / prettier
- [x] Add LICENSE file
- [x] Switch to use national parks dataset
- [x] Publish import script and update command to npx

Not doing now:
- [ ] Switch to main from master
- [ ] Build a more resilient import script - base it on App Search bulk importer / the big query extension importer
- [ ] Add an example project that uses search
